### ISSUE TITLE
Issues Linking To Tenant While Sharding

### ISSUE THREAD

**Issue by akema-trebla** [JonPSmith/AuthPermissions.AspNetCore#120]
I have the following error while enabling linking to tenant when sharding is being used:

System.ArgumentNullException: Value cannot be null. (Parameter '_cookiesIn')
         at AuthPermissions.AspNetCore.AccessTenantData.Services.AccessTenantDataCookie.GetValue() in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/AccessTenantData/Services/AccessTenantDataCookie.cs:line 65
         at AuthPermissions.AspNetCore.AccessTenantData.Services.LinkToTenantDataService.GetShardingDataOfLinkedTenant() in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/AccessTenantData/Services/LinkToTenantDataService.cs:line 128
         at AuthPermissions.AspNetCore.GetDataKeyCode.GetShardingDataUserAccessTenantData..ctor(IHttpContextAccessor accessor, IGetSetShardingEntries connectionService, ILinkToTenantDataService linkService) in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/GetDataKeyCode/GetShardingDataUserAccessTenantData.cs:line 30
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at AuthPermissions.AspNetCore.StartupServices.StartupServiceMigrateAnyDbContext`1.ApplyYourChangeAsync(IServiceProvider scopedServices) in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/StartupServices/StartupServiceMigrateAnyDbContext.cs:line 29
         at RunMethodsSequentially.LockAndRunCode.JobRunner.RunJobAsync(IServiceProvider scopedServices)
         at RunMethodsSequentially.LockAndRunCode.FileSystemLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
         at RunMethodsSequentially.LockAndRunCode.FileSystemLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
         at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunServices.LockAndLoadAsync()
         at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunHostedService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter '_cookiesIn')
   at AuthPermissions.AspNetCore.AccessTenantData.Services.AccessTenantDataCookie.GetValue() in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/AccessTenantData/Services/AccessTenantDataCookie.cs:line 65
   at AuthPermissions.AspNetCore.AccessTenantData.Services.LinkToTenantDataService.GetShardingDataOfLinkedTenant() in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/AccessTenantData/Services/LinkToTenantDataService.cs:line 128
   at AuthPermissions.AspNetCore.GetDataKeyCode.GetShardingDataUserAccessTenantData..ctor(IHttpContextAccessor accessor, IGetSetShardingEntries connectionService, ILinkToTenantDataService linkService) in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/GetDataKeyCode/GetShardingDataUserAccessTenantData.cs:line 30
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at AuthPermissions.AspNetCore.StartupServices.StartupServiceMigrateAnyDbContext`1.ApplyYourChangeAsync(IServiceProvider scopedServices) in /Users/akema_trebla/Downloads/AuthPermissions.AspNetCore-main 2/AuthPermissions.AspNetCore/StartupServices/StartupServiceMigrateAnyDbContext.cs:line 29
   at RunMethodsSequentially.LockAndRunCode.JobRunner.RunJobAsync(IServiceProvider scopedServices)
   at RunMethodsSequentially.LockAndRunCode.FileSystemLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.FileSystemLockAndRunJob.LockAndRunMethodsAsync(IServiceProvider serviceProvider)
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunServices.LockAndLoadAsync()
   at RunMethodsSequentially.LockAndRunCode.GetLockAndThenRunHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>

**Comment by JonPSmith** [comment]
Hi @akema-trebla,

The exception says that there is no cookie. This happens when the application starts up. One obvious reason is if you a browser that doesn't supports cookies as Example6 uses cookies (not WebAPI).

**Comment by akema-trebla** [comment]
Hi @JonPSmith 

Works fine without an error if I use Example 3 where there is no sharding. The issue comes up at startup when using Example 6 which has sharding. That's how I know it's an issue once sharding is introduced.

**Comment by JonPSmith** [comment]
Each Examples has a different features, and Example6 uses the [`AccessTenantDataCookie`](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions.AspNetCore/AccessTenantData/Services/AccessTenantDataCookie.cs) to allows an Admin user to select any tenant by using adding a new Cookie. Example3 also uses the `AccessTenantDataCookie` too, but the `options.LinkToTenantType = LinkToTenantTypes.OnlyAppUsers;`, while Example6 has uses the default settings, which uses a cookie.

So, add `options.LinkToTenantType = LinkToTenantTypes.OnlyAppUsers` in the `builder.Services.RegisterAuthPermissions<...>(options =>` in your Program to turn off the Admin user ability to see any Tenant. 

NOTE: Example6 has a lots of the more complex services so its not a good one to choose. I recommend you read the [Part6: Using sharding to build multi-tenant apps using ASP.NET Core and EF Core](https://www.thereformedprogrammer.net/part6-using-sharding-to-build-multi-tenant-apps-using-asp-net-core-and-ef-core/) and [The (long) journey to a better sharding multi-tenant application](https://www.thereformedprogrammer.net/the-long-journey-to-a-better-sharding-multi-tenant-application/)
